// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJK8IB2PcwOknqRFcTflNCcpDgcJSs8II',
    appId: '1:787779393187:web:b30d446f8d9c35c8e09116',
    messagingSenderId: '787779393187',
    projectId: 'socialapp-be078',
    authDomain: 'socialapp-be078.firebaseapp.com',
    storageBucket: 'socialapp-be078.appspot.com',
    measurementId: 'G-4YH3C5TZDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTWbj6sypGQEwinzjaV1i4IGgfMim6mtk',
    appId: '1:787779393187:android:f79e317ed2d3b3b0e09116',
    messagingSenderId: '787779393187',
    projectId: 'socialapp-be078',
    storageBucket: 'socialapp-be078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVPwP8HEg9lezvr-i2taYX2sLss8WWfi4',
    appId: '1:787779393187:ios:673ee5e4026e8049e09116',
    messagingSenderId: '787779393187',
    projectId: 'socialapp-be078',
    storageBucket: 'socialapp-be078.appspot.com',
    iosBundleId: 'com.example.socialAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVPwP8HEg9lezvr-i2taYX2sLss8WWfi4',
    appId: '1:787779393187:ios:6bb2532341e2d0bfe09116',
    messagingSenderId: '787779393187',
    projectId: 'socialapp-be078',
    storageBucket: 'socialapp-be078.appspot.com',
    iosBundleId: 'com.example.socialAppDemo.RunnerTests',
  );
}
